root: true
parser: '@typescript-eslint/parser'
parserOptions:
    tsconfigRootDir: '.'
    project: 
        - tsconfig.json
    ecmaVersion: 'latest'

env:
    browser: true
    node: true
    es6: true

plugins: 
    - import
    - simple-import-sort
    - '@typescript-eslint'

extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - plugin:@typescript-eslint/recommended-requiring-type-checking
    - plugin:react/recommended
    - plugin:react/jsx-runtime
    - plugin:react-hooks/recommended
    - plugin:jsx-a11y/recommended
    - prettier

ignorePatterns: 
    - 'tools/*'
    - vite.config.ts

rules: 
    simple-import-sort/imports: error
    simple-import-sort/exports: error
    import/first: error
    import/newline-after-import: error
    import/no-duplicates: error
    jsx-a11y/click-events-have-key-events: off
    jsx-a11y/no-static-element-interactions: off
    '@typescript-eslint/no-misused-promises':
        - error
        - checksVoidReturn: false

settings:
    import/parsers:
        '@typescript-eslint/parser': 
            - .ts

    import/resolver:
        typescript:
            alwaysTryTypes: true
            project: tsconfig.json
    react:
        version: detect
