export default [
  { label: 'ALL: Include All Departments', value: 'ALL' },
  { label: 'AC ENG: Academic English & ESL', value: 'AC ENG' },
  { label: 'AFAM: African American Studies', value: 'AFAM' },
  { label: 'ANATOMY: Anatomy & Neurobiology', value: 'ANATOMY' },
  { label: 'ANESTH: Anesthesiology', value: 'ANESTH' },
  { label: 'ANTHRO: Anthropology', value: 'ANTHRO' },
  { label: 'ARABIC: Arabic', value: 'ARABIC' },
  { label: 'ARMN: Armenian', value: 'ARMN' },
  { label: 'ART: Art', value: 'ART' },
  { label: 'ART HIS: Art History', value: 'ART HIS' },
  { label: 'ARTS: Arts', value: 'ARTS' },
  { label: 'ARTSHUM: Arts and Humanities', value: 'ARTSHUM' },
  { label: 'ASIANAM: Asian American Studies', value: 'ASIANAM' },
  { label: 'BANA: Business Analytics', value: 'BANA' },
  { label: 'BATS: Biomedical and Translational Science', value: 'BATS' },
  { label: 'BIO SCI: Biological Sciences', value: 'BIO SCI' },
  { label: 'BIOCHEM: Biological Chemistry', value: 'BIOCHEM' },
  { label: 'BME: Biomedical Engineering', value: 'BME' },
  { label: 'CAMPREC: Campus Recreation', value: 'CAMPREC' },
  {
    label: 'CBE: Chemical and Biomolecular Engineering (Since F18)',
    value: 'CBE',
  },
  { label: 'CBEMS: Chemical Engr and Materials Science', value: 'CBEMS' },
  { label: 'CEM: Community and Environmental Medicine', value: 'CEM' },
  { label: 'CHC/LAT: Chicano Latino', value: 'CHC/LAT' },
  { label: 'CHEM: Chemistry', value: 'CHEM' },
  { label: 'CHINESE: Chinese', value: 'CHINESE' },
  { label: 'CLASSIC: Classics', value: 'CLASSIC' },
  { label: 'CLT&THY: Culture & Theory', value: 'CLT&THY' },
  { label: 'COGS: Cognitive Sciences ', value: 'COGS' },
  { label: 'COM LIT: Comparative Literature', value: 'COM LIT' },
  { label: 'COMPSCI: Computer Science', value: 'COMPSCI' },
  { label: 'CRITISM: Criticism', value: 'CRITISM' },
  { label: 'CRM/LAW: Criminology, Law and Society', value: 'CRM/LAW' },
  { label: 'CSE: Computer Science and Engineering', value: 'CSE' },
  { label: 'DANCE: Dance', value: 'DANCE' },
  { label: 'DERM: Dermatology', value: 'DERM' },
  { label: 'DEV BIO: Developmental & Cell Biology', value: 'DEV BIO' },
  { label: 'DRAMA: Drama', value: 'DRAMA' },
  { label: 'E ASIAN: East Asian Languages & Literatures', value: 'E ASIAN' },
  { label: 'EARTHSS: Earth System Science', value: 'EARTHSS' },
  { label: 'EAS: East Asian Studies (Since F19)', value: 'EAS' },
  { label: 'ECO EVO: Ecology & Evolutionary Biology', value: 'ECO EVO' },
  { label: 'ECON: Economics', value: 'ECON' },
  { label: 'ECPS: Embedded & Cyber-Physical Systems', value: 'ECPS' },
  { label: 'ED AFF: Educational Affairs (Med School)', value: 'ED AFF' },
  { label: 'EDUC: Education', value: 'EDUC' },
  { label: 'EECS: Electrical Engineering & Computer Science', value: 'EECS' },
  { label: 'EHS: Environmental Health Sciences', value: 'EHS' },
  { label: 'ENGLISH: English', value: 'ENGLISH' },
  { label: 'ENGR: Engineering', value: 'ENGR' },
  { label: 'ENGRCEE: Engineering, Civil & Environmental', value: 'ENGRCEE' },
  { label: 'ENGRMAE: Engineering, Mechanical & Aerospace', value: 'ENGRMAE' },
  {
    label: 'ENGRMSE: Chemical Engr & Materials Science (Grad)',
    value: 'ENGRMSE',
  },
  { label: 'EPIDEM: Epidemiology', value: 'EPIDEM' },
  { label: 'ER MED: Emergency Medicine', value: 'ER MED' },
  { label: 'EURO ST: European Studies', value: 'EURO ST' },
  { label: 'FAM MED: Family Medicine', value: 'FAM MED' },
  { label: 'FIN: Finance', value: 'FIN' },
  { label: 'FLM&MDA: Film & Media Studies', value: 'FLM&MDA' },
  { label: 'FRENCH: French', value: 'FRENCH' },
  { label: 'GEN&SEX: Gender & Sexuality Studies', value: 'GEN&SEX' },
  { label: 'GERMAN: German', value: 'GERMAN' },
  { label: 'GLBL ME: Global Middle East Studies', value: 'GLBL ME' },
  { label: 'GLBLCLT: Global Cultures', value: 'GLBLCLT' },
  { label: 'GREEK: Greek', value: 'GREEK' },
  { label: 'HEBREW: Hebrew', value: 'HEBREW' },
  { label: 'HINDI: Hindi', value: 'HINDI' },
  { label: 'HISTORY: History', value: 'HISTORY' },
  { label: 'HUMAN: Humanities', value: 'HUMAN' },
  { label: 'HUMARTS: Humanities & Arts', value: 'HUMARTS' },
  { label: 'I&C SCI (ICS): Information & Computer Science', value: 'I&C SCI' },
  { label: 'IN4MATX: Informatics', value: 'IN4MATX' },
  { label: 'INT MED: Internal Medicine', value: 'INT MED' },
  { label: 'INTL ST: International Studies', value: 'INTL ST' },
  { label: 'ITALIAN: Italian', value: 'ITALIAN' },
  { label: 'JAPANSE: Japanese', value: 'JAPANSE' },
  { label: 'KOREAN: Korean', value: 'KOREAN' },
  { label: 'LATIN: Latin', value: 'LATIN' },
  { label: 'LAW: Law', value: 'LAW' },
  { label: 'LINGUIS: Linguistics', value: 'LINGUIS' },
  { label: 'LIT JRN: Literary Journalism', value: 'LIT JRN' },
  { label: 'LPS: Logic & Philosophy of Science', value: 'LPS' },
  { label: 'LSCI: Language Science (Since F19)', value: 'LSCI' },
  { label: 'M&MG (MMG): Microbiology & Molecular Genetics', value: 'M&MG' },
  { label: 'MATH: Mathematics', value: 'MATH' },
  { label: 'MED: Medicine', value: 'MED' },
  { label: 'MED ED: Medical Education', value: 'MED ED' },
  { label: 'MED HUM: Medical Humanities', value: 'MED HUM' },
  { label: 'MGMT: Management', value: 'MGMT' },
  { label: 'MGMT EP: Executive MBA', value: 'MGMT EP' },
  { label: 'MGMT FE: Fully Employed MBA', value: 'MGMT FE' },
  { label: 'MGMT HC: Health Care MBA', value: 'MGMT HC' },
  { label: 'MGMTMBA: Managemt MBA', value: 'MGMTMBA' },
  { label: 'MGMTPHD: Managemt PhD', value: 'MGMTPHD' },
  { label: 'MIC BIO: Microbiology', value: 'MIC BIO' },
  { label: 'MOL BIO: Molecular Biology & Biochemistry', value: 'MOL BIO' },
  { label: 'MPAC: Accounting', value: 'MPAC' },
  { label: 'MSE: Materials Science and Engineering (F18-F18)', value: 'MSE' },
  { label: 'MUSIC: Music', value: 'MUSIC' },
  { label: 'NET SYS: Networked Systems', value: 'NET SYS' },
  { label: 'NEURBIO: Neurobiology & Behavior', value: 'NEURBIO' },
  { label: 'NEUROL: Neurology', value: 'NEUROL' },
  { label: 'NUR SCI: Nursing Science', value: 'NUR SCI' },
  { label: 'OB/GYN: Obstetrics and Gynecology', value: 'OB/GYN' },
  { label: 'OPHTHAL: Ophthalmology', value: 'OPHTHAL' },
  { label: 'PATH: Pathology and Laboratory Medicine', value: 'PATH' },
  { label: 'PED GEN: Pediatrics Genetics', value: 'PED GEN' },
  { label: 'PEDS: Pediatrics', value: 'PEDS' },
  { label: 'PERSIAN: Persian', value: 'PERSIAN' },
  { label: 'PHARM: Medical Pharmacology', value: 'PHARM' },
  { label: 'PHILOS: Philosophy', value: 'PHILOS' },
  { label: 'PHRMSCI: Pharmaceutical Sciences', value: 'PHRMSCI' },
  { label: 'PHY SCI: Physical Science', value: 'PHY SCI' },
  { label: 'PHYSICS: Physics', value: 'PHYSICS' },
  { label: 'PHYSIO: Physiology & Biophysics', value: 'PHYSIO' },
  { label: 'PLASTIC: Plastic Surgery', value: 'PLASTIC' },
  { label: 'PM&R (PMR): Physical Medicine & Rehabilitation', value: 'PM&R' },
  { label: 'POL SCI: Political Science', value: 'POL SCI' },
  { label: 'PORTUG: Portuguese', value: 'PORTUG' },
  { label: 'PSCI: Psychological Science (Since F19)', value: 'PSCI' },
  { value: 'PSY BEH', label: 'PSY BEH: Psychology & Social Behavior' },
  { value: 'PSYCH', label: 'PSYCH: Psychology' },
  { value: 'PUB POL', label: 'PUB POL: Public Policy' },
  { value: 'PUBHLTH', label: 'PUBHLTH: Public Health' },
  { value: 'RADIO', label: 'RADIO: Radiology' },
  { value: 'REL STD', label: 'REL STD: Religious Studies' },
  { value: 'ROTC', label: "ROTC: Reserve Officers' Training Corps" },
  { value: 'RUSSIAN', label: 'RUSSIAN: Russian' },
  { value: 'SOC SCI', label: 'SOC SCI: Social Science' },
  { value: 'SOCECOL', label: 'SOCECOL: Social Ecology' },
  { value: 'SOCIOL', label: 'SOCIOL: Sociology' },
  { value: 'SPANISH', label: 'SPANISH: Spanish' },
  { value: 'SPPS', label: 'SPPS: Social Policy & Public Service' },
  { value: 'STATS', label: 'STATS: Statistics' },
  { value: 'SURGERY', label: 'SURGERY: Surgery' },
  { value: 'SWE', label: 'SWE: Software Engineering (Since F19)' },
  { value: 'TAGALOG', label: 'TAGALOG: Tagalog' },
  { value: 'TOX', label: 'TOX: Toxicology' },
  { value: 'UCDC', label: 'UCDC: UC Washington DC' },
  { value: 'UNI AFF', label: 'UNI AFF: University Affairs' },
  { value: 'UNI STU', label: 'UNI STU: University Studies' },
  { label: 'UPPP: Urban Planning & Public Policy', value: 'UPPP' },
  { label: 'VIETMSE: Vietnamese', value: 'VIETMSE' },
  { label: 'VIS STD: Visual Studies', value: 'VIS STD' },
  { label: 'WRITING: Writing', value: 'WRITING' },
];
