export default [
    { deptLabel: 'ALL: Include All Departments', deptValue: 'ALL' },
    { deptLabel: 'AC ENG: Academic English and ESL', deptValue: 'AC ENG' },
    { deptLabel: 'AFAM: African American Studies', deptValue: 'AFAM' },
    { deptLabel: 'ANATOMY: Anatomy and Neurobiology', deptValue: 'ANATOMY' },
    { deptLabel: 'ANESTH: Anesthesiology', deptValue: 'ANESTH' },
    { deptLabel: 'ANTHRO: Anthropology', deptValue: 'ANTHRO' },
    { deptLabel: 'ARABIC: Arabic', deptValue: 'ARABIC' },
    { deptLabel: 'ARMN: Armenian', deptValue: 'ARMN' },
    { deptLabel: 'ART: Art', deptValue: 'ART' },
    { deptLabel: 'ART HIS: Art History', deptValue: 'ART HIS' },
    { deptLabel: 'ARTS: Arts', deptValue: 'ARTS' },
    { deptLabel: 'ARTSHUM: Arts and Humanities', deptValue: 'ARTSHUM' },
    { deptLabel: 'ASIANAM: Asian American Studies', deptValue: 'ASIANAM' },
    { deptLabel: 'BANA: Business Analytics', deptValue: 'BANA' },
    { deptLabel: 'BATS: Biomedical and Translational Science', deptValue: 'BATS' },
    { deptLabel: 'BIO SCI: Biological Sciences', deptValue: 'BIO SCI' },
    { deptLabel: 'BIOCHEM: Biological Chemistry', deptValue: 'BIOCHEM' },
    { deptLabel: 'BME: Biomedical Engineering', deptValue: 'BME' },
    { deptLabel: 'CAMPREC: Campus Recreation', deptValue: 'CAMPREC' },
    { deptLabel: 'CBE: Chemical and Biomolecular Engineering', deptValue: 'CBE' },
    { deptLabel: 'CEM: Community and Environmental Medicine', deptValue: 'CEM' },
    { deptLabel: 'CHC/LAT: Chicano Latino', deptValue: 'CHC/LAT' },
    { deptLabel: 'CHEM: Chemistry', deptValue: 'CHEM' },
    { deptLabel: 'CHINESE: Chinese', deptValue: 'CHINESE' },
    { deptLabel: 'CLASSIC: Classics', deptValue: 'CLASSIC' },
    { deptLabel: 'CLT&THY: Culture & Theory', deptValue: 'CLT&THY' },
    { deptLabel: 'COGS: Cognitive Sciences', deptValue: 'COGS' },
    { deptLabel: 'COM LIT: Comparative Literature', deptValue: 'COM LIT' },
    { deptLabel: 'COMPSCI: Computer Science', deptValue: 'COMPSCI' },
    { deptLabel: 'CRITISM: Criticism', deptValue: 'CRITISM' },
    { deptLabel: 'CRM/LAW: Criminology, Law and Society', deptValue: 'CRM/LAW' },
    { deptLabel: 'CSE: Computer Science and Engineering', deptValue: 'CSE' },
    { deptLabel: 'DANCE: Dance', deptValue: 'DANCE' },
    { deptLabel: 'DERM: Dermatology', deptValue: 'DERM' },
    { deptLabel: 'DEV BIO: Developmental and Cell Biology', deptValue: 'DEV BIO' },
    { deptLabel: 'DRAMA: Drama', deptValue: 'DRAMA' },
    { deptLabel: 'EARTHSS: Earth System Science', deptValue: 'EARTHSS' },
    { deptLabel: 'EAS: East Asian Studies', deptValue: 'EAS' },
    { deptLabel: 'ECO EVO: Ecology and Evolutionary Biology', deptValue: 'ECO EVO' },
    { deptLabel: 'ECON: Economics', deptValue: 'ECON' },
    { deptLabel: 'ECPS: Embedded and Cyber-Physical Systems', deptValue: 'ECPS' },
    { deptLabel: 'ED AFF: Educational Affairs (Sch of Med)', deptValue: 'ED AFF' },
    { deptLabel: 'EDUC: Education', deptValue: 'EDUC' },
    { deptLabel: 'EECS: Electrical Engineering & Computer Science', deptValue: 'EECS' },
    { deptLabel: 'EHS: Environmental Health Sciences', deptValue: 'EHS' },
    { deptLabel: 'ENGLISH: English', deptValue: 'ENGLISH' },
    { deptLabel: 'ENGR: Engineering', deptValue: 'ENGR' },
    { deptLabel: 'ENGRCEE: Engineering, Civil and Environmental', deptValue: 'ENGRCEE' },
    { deptLabel: 'ENGRMAE: Engineering, Mechanical and Aerospace', deptValue: 'ENGRMAE' },
    { deptLabel: 'EPIDEM: Epidemiology', deptValue: 'EPIDEM' },
    { deptLabel: 'ER MED: Emergency Medicine', deptValue: 'ER MED' },
    { deptLabel: 'EURO ST: European Studies', deptValue: 'EURO ST' },
    { deptLabel: 'FAM MED: Family Medicine', deptValue: 'FAM MED' },
    { deptLabel: 'FIN: Finance', deptValue: 'FIN' },
    { deptLabel: 'FLM&MDA: Film and Media Studies', deptValue: 'FLM&MDA' },
    { deptLabel: 'FRENCH: French', deptValue: 'FRENCH' },
    { deptLabel: 'GDIM: Game Design and Interactive Media', deptValue: 'GDIM' },
    { deptLabel: 'GEN&SEX: Gender and Sexuality Studies', deptValue: 'GEN&SEX' },
    { deptLabel: 'GERMAN: German', deptValue: 'GERMAN' },
    { deptLabel: 'GLBL ME: Global Middle East Studies', deptValue: 'GLBL ME' },
    { deptLabel: 'GLBLCLT: Global Cultures', deptValue: 'GLBLCLT' },
    { deptLabel: 'GREEK: Greek', deptValue: 'GREEK' },
    { deptLabel: 'HEBREW: Hebrew', deptValue: 'HEBREW' },
    { deptLabel: 'HINDI: Hindi', deptValue: 'HINDI' },
    { deptLabel: 'HISTORY: History', deptValue: 'HISTORY' },
    { deptLabel: 'HUMAN: Humanities', deptValue: 'HUMAN' },
    { deptLabel: 'HUMARTS: Humanities and Arts', deptValue: 'HUMARTS' },
    { deptLabel: 'I&C SCI: Information and Computer Science', deptValue: 'I&C SCI' },
    { deptLabel: 'IN4MATX: Informatics', deptValue: 'IN4MATX' },
    { deptLabel: 'INNO: Masters of Innovation and Entrepreneurship', deptValue: 'INNO' },
    { deptLabel: 'INT MED: Internal Medicine', deptValue: 'INT MED' },
    { deptLabel: 'INTL ST: International Studies', deptValue: 'INTL ST' },
    { deptLabel: 'IRAN: Iranian', deptValue: 'IRAN' },
    { deptLabel: 'ITALIAN: Italian', deptValue: 'ITALIAN' },
    { deptLabel: 'JAPANSE: Japanese', deptValue: 'JAPANSE' },
    { deptLabel: 'KOREAN: Korean', deptValue: 'KOREAN' },
    { deptLabel: 'LATIN: Latin', deptValue: 'LATIN' },
    { deptLabel: 'LAW: Law', deptValue: 'LAW' },
    { deptLabel: 'LIT JRN: Literary Journalism', deptValue: 'LIT JRN' },
    { deptLabel: 'LPS: Logic and Philosophy of Science', deptValue: 'LPS' },
    { deptLabel: 'LSCI: Language Science', deptValue: 'LSCI' },
    { deptLabel: 'M&MG: Microbiology and Molecular Genetics', deptValue: 'M&MG' },
    { deptLabel: 'MATH: Mathematics', deptValue: 'MATH' },
    { deptLabel: 'MED: Medicine', deptValue: 'MED' },
    { deptLabel: 'MED ED: Medical Education', deptValue: 'MED ED' },
    { deptLabel: 'MED HUM: Medical Humanities', deptValue: 'MED HUM' },
    { deptLabel: 'MGMT: Management', deptValue: 'MGMT' },
    { deptLabel: 'MGMT EP: Executive MBA', deptValue: 'MGMT EP' },
    { deptLabel: 'MGMT FE: Fully Employed MBA', deptValue: 'MGMT FE' },
    { deptLabel: 'MGMT HC: Health Care MBA', deptValue: 'MGMT HC' },
    { deptLabel: 'MGMTMBA: Management MBA', deptValue: 'MGMTMBA' },
    { deptLabel: 'MGMTPHD: Management PhD', deptValue: 'MGMTPHD' },
    { deptLabel: 'MIC BIO: Microbiology', deptValue: 'MIC BIO' },
    { deptLabel: 'MOL BIO: Molecular Biology and Biochemistry', deptValue: 'MOL BIO' },
    { deptLabel: 'MPAC: Accounting', deptValue: 'MPAC' },
    { deptLabel: 'MSE: Materials Science and Engineering', deptValue: 'MSE' },
    { deptLabel: 'MUSIC: Music', deptValue: 'MUSIC' },
    { deptLabel: 'NET SYS: Networked Systems', deptValue: 'NET SYS' },
    { deptLabel: 'NEURBIO: Neurobiology and Behavior', deptValue: 'NEURBIO' },
    { deptLabel: 'NEUROL: Neurology', deptValue: 'NEUROL' },
    { deptLabel: 'NUR SCI: Nursing Science', deptValue: 'NUR SCI' },
    { deptLabel: 'OB/GYN: Obstetrics and Gynecology', deptValue: 'OB/GYN' },
    { deptLabel: 'OPHTHAL: Ophthalmology', deptValue: 'OPHTHAL' },
    { deptLabel: 'PATH: Pathology and Laboratory Medicine', deptValue: 'PATH' },
    { deptLabel: 'PED GEN: Pediatrics Genetics', deptValue: 'PED GEN' },
    { deptLabel: 'PEDS: Pediatrics', deptValue: 'PEDS' },
    { deptLabel: 'PERSIAN: Persian', deptValue: 'PERSIAN' },
    { deptLabel: 'PHARM: Medical Pharmacology', deptValue: 'PHARM' },
    { deptLabel: 'PHILOS: Philosophy', deptValue: 'PHILOS' },
    { deptLabel: 'PHRMSCI: Pharmaceutical Sciences', deptValue: 'PHRMSCI' },
    { deptLabel: 'PHY SCI: Physical Science', deptValue: 'PHY SCI' },
    { deptLabel: 'PHYSICS: Physics', deptValue: 'PHYSICS' },
    { deptLabel: 'PHYSIO: Physiology and Biophysics', deptValue: 'PHYSIO' },
    { deptLabel: 'PLASTIC: Plastic Surgery', deptValue: 'PLASTIC' },
    { deptLabel: 'PM&R: Physical Medicine and Rehabilitation', deptValue: 'PM&R' },
    { deptLabel: 'POL SCI: Political Science', deptValue: 'POL SCI' },
    { deptLabel: 'PORTUG: Portuguese', deptValue: 'PORTUG' },
    { deptLabel: 'PSCI: Psychological Science', deptValue: 'PSCI' },
    { deptLabel: 'PSYCH: Psychology', deptValue: 'PSYCH' },
    { deptLabel: 'PUB POL: Public Policy', deptValue: 'PUB POL' },
    { deptLabel: 'PUBHLTH: Public Health', deptValue: 'PUBHLTH' },
    { deptLabel: 'RADIO: Radiology', deptValue: 'RADIO' },
    { deptLabel: 'REL STD: Religious Studies', deptValue: 'REL STD' },
    { deptLabel: "ROTC: Reserve Officers' Training Corps", deptValue: 'ROTC' },
    { deptLabel: 'RUSSIAN: Russian', deptValue: 'RUSSIAN' },
    { deptLabel: 'SOC SCI: Social Science', deptValue: 'SOC SCI' },
    { deptLabel: 'SOCECOL: Social Ecology', deptValue: 'SOCECOL' },
    { deptLabel: 'SOCIOL: Sociology', deptValue: 'SOCIOL' },
    { deptLabel: 'SPANISH: Spanish', deptValue: 'SPANISH' },
    { deptLabel: 'SPPS: Social Policy & Public Service', deptValue: 'SPPS' },
    { deptLabel: 'STATS: Statistics', deptValue: 'STATS' },
    { deptLabel: 'SURGERY: Surgery', deptValue: 'SURGERY' },
    { deptLabel: 'SWE: Software Engineering', deptValue: 'SWE' },
    { deptLabel: 'TAGALOG: Tagalog', deptValue: 'TAGALOG' },
    { deptLabel: 'TOX: Toxicology', deptValue: 'TOX' },
    { deptLabel: 'UCDC: UC Washington DC', deptValue: 'UCDC' },
    { deptLabel: 'UNI AFF: University Affairs', deptValue: 'UNI AFF' },
    { deptLabel: 'UNI STU: University Studies', deptValue: 'UNI STU' },
    { deptLabel: 'UPPP: Urban Planning and Public Policy', deptValue: 'UPPP' },
    { deptLabel: 'VIETMSE: Vietnamese', deptValue: 'VIETMSE' },
    { deptLabel: 'VIS STD: Visual Studies', deptValue: 'VIS STD' },
    { deptLabel: 'WRITING: Writing', deptValue: 'WRITING' },
];
