export default [
    { deptLabel: 'ALL: Include All Departments', deptValue: 'ALL' },
    { deptLabel: 'AC ENG: Academic English & ESL', deptValue: 'AC ENG' },
    { deptLabel: 'AFAM: African American Studies', deptValue: 'AFAM' },
    { deptLabel: 'ANATOMY: Anatomy & Neurobiology', deptValue: 'ANATOMY' },
    { deptLabel: 'ANESTH: Anesthesiology', deptValue: 'ANESTH' },
    { deptLabel: 'ANTHRO: Anthropology', deptValue: 'ANTHRO' },
    { deptLabel: 'ARABIC: Arabic', deptValue: 'ARABIC' },
    { deptLabel: 'ARMN: Armenian', deptValue: 'ARMN' },
    { deptLabel: 'ART: Art', deptValue: 'ART' },
    { deptLabel: 'ART HIS: Art History', deptValue: 'ART HIS' },
    { deptLabel: 'ARTS: Arts', deptValue: 'ARTS' },
    { deptLabel: 'ARTSHUM: Arts and Humanities', deptValue: 'ARTSHUM' },
    { deptLabel: 'ASIANAM: Asian American Studies', deptValue: 'ASIANAM' },
    { deptLabel: 'BANA: Business Analytics', deptValue: 'BANA' },
    { deptLabel: 'BATS: Biomedical and Translational Science', deptValue: 'BATS' },
    { deptLabel: 'BIO SCI: Biological Sciences', deptValue: 'BIO SCI' },
    { deptLabel: 'BIOCHEM: Biological Chemistry', deptValue: 'BIOCHEM' },
    { deptLabel: 'BME: Biomedical Engineering', deptValue: 'BME' },
    { deptLabel: 'CAMPREC: Campus Recreation', deptValue: 'CAMPREC' },
    { deptLabel: 'CBE: Chemical and Biomolecular Engineering (Since F18)', deptValue: 'CBE' },
    { deptLabel: 'CBEMS: Chemical Engr and Materials Science', deptValue: 'CBEMS' },
    { deptLabel: 'CEM: Community and Environmental Medicine', deptValue: 'CEM' },
    { deptLabel: 'CHC/LAT: Chicano Latino', deptValue: 'CHC/LAT' },
    { deptLabel: 'CHEM: Chemistry', deptValue: 'CHEM' },
    { deptLabel: 'CHINESE: Chinese', deptValue: 'CHINESE' },
    { deptLabel: 'CLASSIC: Classics', deptValue: 'CLASSIC' },
    { deptLabel: 'CLT&THY: Culture & Theory', deptValue: 'CLT&THY' },
    { deptLabel: 'COGS: Cognitive Sciences ', deptValue: 'COGS' },
    { deptLabel: 'COM LIT: Comparative Literature', deptValue: 'COM LIT' },
    { deptLabel: 'COMPSCI: Computer Science', deptValue: 'COMPSCI' },
    { deptLabel: 'CRITISM: Criticism', deptValue: 'CRITISM' },
    { deptLabel: 'CRM/LAW: Criminology, Law and Society', deptValue: 'CRM/LAW' },
    { deptLabel: 'CSE: Computer Science and Engineering', deptValue: 'CSE' },
    { deptLabel: 'DANCE: Dance', deptValue: 'DANCE' },
    { deptLabel: 'DERM: Dermatology', deptValue: 'DERM' },
    { deptLabel: 'DEV BIO: Developmental & Cell Biology', deptValue: 'DEV BIO' },
    { deptLabel: 'DRAMA: Drama', deptValue: 'DRAMA' },
    { deptLabel: 'E ASIAN: East Asian Languages & Literatures', deptValue: 'E ASIAN' },
    { deptLabel: 'EARTHSS: Earth System Science', deptValue: 'EARTHSS' },
    { deptLabel: 'EAS: East Asian Studies (Since F19)', deptValue: 'EAS' },
    { deptLabel: 'ECO EVO: Ecology & Evolutionary Biology', deptValue: 'ECO EVO' },
    { deptLabel: 'ECON: Economics', deptValue: 'ECON' },
    { deptLabel: 'ECPS: Embedded & Cyber-Physical Systems', deptValue: 'ECPS' },
    { deptLabel: 'ED AFF: Educational Affairs (Med School)', deptValue: 'ED AFF' },
    { deptLabel: 'EDUC: Education', deptValue: 'EDUC' },
    { deptLabel: 'EECS: Electrical Engineering & Computer Science', deptValue: 'EECS' },
    { deptLabel: 'EHS: Environmental Health Sciences', deptValue: 'EHS' },
    { deptLabel: 'ENGLISH: English', deptValue: 'ENGLISH' },
    { deptLabel: 'ENGR: Engineering', deptValue: 'ENGR' },
    { deptLabel: 'ENGRCEE: Engineering, Civil & Environmental', deptValue: 'ENGRCEE' },
    { deptLabel: 'ENGRMAE: Engineering, Mechanical & Aerospace', deptValue: 'ENGRMAE' },
    { deptLabel: 'ENGRMSE: Chemical Engr & Materials Science (Grad)', deptValue: 'ENGRMSE' },
    { deptLabel: 'EPIDEM: Epidemiology', deptValue: 'EPIDEM' },
    { deptLabel: 'ER MED: Emergency Medicine', deptValue: 'ER MED' },
    { deptLabel: 'EURO ST: European Studies', deptValue: 'EURO ST' },
    { deptLabel: 'FAM MED: Family Medicine', deptValue: 'FAM MED' },
    { deptLabel: 'FIN: Finance', deptValue: 'FIN' },
    { deptLabel: 'FLM&MDA: Film & Media Studies', deptValue: 'FLM&MDA' },
    { deptLabel: 'FRENCH: French', deptValue: 'FRENCH' },
    { deptLabel: 'GEN&SEX: Gender & Sexuality Studies', deptValue: 'GEN&SEX' },
    { deptLabel: 'GERMAN: German', deptValue: 'GERMAN' },
    { deptLabel: 'GLBL ME: Global Middle East Studies', deptValue: 'GLBL ME' },
    { deptLabel: 'GLBLCLT: Global Cultures', deptValue: 'GLBLCLT' },
    { deptLabel: 'GREEK: Greek', deptValue: 'GREEK' },
    { deptLabel: 'HEBREW: Hebrew', deptValue: 'HEBREW' },
    { deptLabel: 'HINDI: Hindi', deptValue: 'HINDI' },
    { deptLabel: 'HISTORY: History', deptValue: 'HISTORY' },
    { deptLabel: 'HUMAN: Humanities', deptValue: 'HUMAN' },
    { deptLabel: 'HUMARTS: Humanities & Arts', deptValue: 'HUMARTS' },
    { deptLabel: 'I&C SCI (ICS): Information & Computer Science', deptValue: 'I&C SCI' },
    { deptLabel: 'IN4MATX: Informatics', deptValue: 'IN4MATX' },
    { deptLabel: 'INT MED: Internal Medicine', deptValue: 'INT MED' },
    { deptLabel: 'INTL ST: International Studies', deptValue: 'INTL ST' },
    { deptLabel: 'ITALIAN: Italian', deptValue: 'ITALIAN' },
    { deptLabel: 'JAPANSE: Japanese', deptValue: 'JAPANSE' },
    { deptLabel: 'KOREAN: Korean', deptValue: 'KOREAN' },
    { deptLabel: 'LATIN: Latin', deptValue: 'LATIN' },
    { deptLabel: 'LAW: Law', deptValue: 'LAW' },
    { deptLabel: 'LINGUIS: Linguistics', deptValue: 'LINGUIS' },
    { deptLabel: 'LIT JRN: Literary Journalism', deptValue: 'LIT JRN' },
    { deptLabel: 'LPS: Logic & Philosophy of Science', deptValue: 'LPS' },
    { deptLabel: 'LSCI: Language Science (Since F19)', deptValue: 'LSCI' },
    { deptLabel: 'M&MG (MMG): Microbiology & Molecular Genetics', deptValue: 'M&MG' },
    { deptLabel: 'MATH: Mathematics', deptValue: 'MATH' },
    { deptLabel: 'MED: Medicine', deptValue: 'MED' },
    { deptLabel: 'MED ED: Medical Education', deptValue: 'MED ED' },
    { deptLabel: 'MED HUM: Medical Humanities', deptValue: 'MED HUM' },
    { deptLabel: 'MGMT: Management', deptValue: 'MGMT' },
    { deptLabel: 'MGMT EP: Executive MBA', deptValue: 'MGMT EP' },
    { deptLabel: 'MGMT FE: Fully Employed MBA', deptValue: 'MGMT FE' },
    { deptLabel: 'MGMT HC: Health Care MBA', deptValue: 'MGMT HC' },
    { deptLabel: 'MGMTMBA: Managemt MBA', deptValue: 'MGMTMBA' },
    { deptLabel: 'MGMTPHD: Managemt PhD', deptValue: 'MGMTPHD' },
    { deptLabel: 'MIC BIO: Microbiology', deptValue: 'MIC BIO' },
    { deptLabel: 'MOL BIO: Molecular Biology & Biochemistry', deptValue: 'MOL BIO' },
    { deptLabel: 'MPAC: Accounting', deptValue: 'MPAC' },
    { deptLabel: 'MSE: Materials Science and Engineering (F18-F18)', deptValue: 'MSE' },
    { deptLabel: 'MUSIC: Music', deptValue: 'MUSIC' },
    { deptLabel: 'NET SYS: Networked Systems', deptValue: 'NET SYS' },
    { deptLabel: 'NEURBIO: Neurobiology & Behavior', deptValue: 'NEURBIO' },
    { deptLabel: 'NEUROL: Neurology', deptValue: 'NEUROL' },
    { deptLabel: 'NUR SCI: Nursing Science', deptValue: 'NUR SCI' },
    { deptLabel: 'OB/GYN: Obstetrics and Gynecology', deptValue: 'OB/GYN' },
    { deptLabel: 'OPHTHAL: Ophthalmology', deptValue: 'OPHTHAL' },
    { deptLabel: 'PATH: Pathology and Laboratory Medicine', deptValue: 'PATH' },
    { deptLabel: 'PED GEN: Pediatrics Genetics', deptValue: 'PED GEN' },
    { deptLabel: 'PEDS: Pediatrics', deptValue: 'PEDS' },
    { deptLabel: 'PERSIAN: Persian', deptValue: 'PERSIAN' },
    { deptLabel: 'PHARM: Medical Pharmacology', deptValue: 'PHARM' },
    { deptLabel: 'PHILOS: Philosophy', deptValue: 'PHILOS' },
    { deptLabel: 'PHRMSCI: Pharmaceutical Sciences', deptValue: 'PHRMSCI' },
    { deptLabel: 'PHY SCI: Physical Science', deptValue: 'PHY SCI' },
    { deptLabel: 'PHYSICS: Physics', deptValue: 'PHYSICS' },
    { deptLabel: 'PHYSIO: Physiology & Biophysics', deptValue: 'PHYSIO' },
    { deptLabel: 'PLASTIC: Plastic Surgery', deptValue: 'PLASTIC' },
    { deptLabel: 'PM&R (PMR): Physical Medicine & Rehabilitation', deptValue: 'PM&R' },
    { deptLabel: 'POL SCI: Political Science', deptValue: 'POL SCI' },
    { deptLabel: 'PORTUG: Portuguese', deptValue: 'PORTUG' },
    { deptLabel: 'PSCI: Psychological Science (Since F19)', deptValue: 'PSCI' },
    { deptValue: 'PSY BEH', deptLabel: 'PSY BEH: Psychology & Social Behavior' },
    { deptValue: 'PSYCH', deptLabel: 'PSYCH: Psychology' },
    { deptValue: 'PUB POL', deptLabel: 'PUB POL: Public Policy' },
    { deptValue: 'PUBHLTH', deptLabel: 'PUBHLTH: Public Health' },
    { deptValue: 'RADIO', deptLabel: 'RADIO: Radiology' },
    { deptValue: 'REL STD', deptLabel: 'REL STD: Religious Studies' },
    { deptValue: 'ROTC', deptLabel: "ROTC: Reserve Officers' Training Corps" },
    { deptValue: 'RUSSIAN', deptLabel: 'RUSSIAN: Russian' },
    { deptValue: 'SOC SCI', deptLabel: 'SOC SCI: Social Science' },
    { deptValue: 'SOCECOL', deptLabel: 'SOCECOL: Social Ecology' },
    { deptValue: 'SOCIOL', deptLabel: 'SOCIOL: Sociology' },
    { deptValue: 'SPANISH', deptLabel: 'SPANISH: Spanish' },
    { deptValue: 'SPPS', deptLabel: 'SPPS: Social Policy & Public Service' },
    { deptValue: 'STATS', deptLabel: 'STATS: Statistics' },
    { deptValue: 'SURGERY', deptLabel: 'SURGERY: Surgery' },
    { deptValue: 'SWE', deptLabel: 'SWE: Software Engineering (Since F19)' },
    { deptValue: 'TAGALOG', deptLabel: 'TAGALOG: Tagalog' },
    { deptValue: 'TOX', deptLabel: 'TOX: Toxicology' },
    { deptValue: 'UCDC', deptLabel: 'UCDC: UC Washington DC' },
    { deptValue: 'UNI AFF', deptLabel: 'UNI AFF: University Affairs' },
    { deptValue: 'UNI STU', deptLabel: 'UNI STU: University Studies' },
    { deptLabel: 'UPPP: Urban Planning & Public Policy', deptValue: 'UPPP' },
    { deptLabel: 'VIETMSE: Vietnamese', deptValue: 'VIETMSE' },
    { deptLabel: 'VIS STD: Visual Studies', deptValue: 'VIS STD' },
    { deptLabel: 'WRITING: Writing', deptValue: 'WRITING' },
];
