name: Create Deployment
description: Workflow for creating deployments within one environment with distinct naming conventions.
inputs:
    GITHUB_TOKEN:
        description: GitHub Actions secret token.
        required: true
    environment:
        description: Environment name for the deployment.
        required: true
    name:
        description: Name of the deployment.
        required: true
    url:
        description: Deployment environment URL.
        required: true
    status:
        description: The deployment status. It's used as the "state" parameter when creating a deployment status.
        required: true
        default: in_progress
    deployment_id:
        description: If referencing an existing deployment, provide the ID to update the status.
        required: false

outputs:
    deployment_id:
        description: Deployment ID.

runs:
    using: 'node20'
    main: 'src/index.js'
