module.exports = [
    {
        url: 'https://facebook.com/ICSStudentCouncil/',
        bannerName: 'ICSSC.jpg',
        dept: ['COMPSCI', 'I&C SCI', 'IN4MATX'],
    },
    {
        url: 'http://www.ucitriangle.com/',
        bannerName: 'Triangle.jpg',
        dept: [
            'BIO SCI',
            'BME',
            'CBE',
            'CHEM',
            'COGS',
            'COMPSCI',
            'CSE',
            'EARTHSS',
            'EECS',
            'ENGR',
            'ENGRCEE',
            'ENGRMAE',
            'I&C SCI',
            'IN4MATX',
            'MATH',
            'PHRMSCI',
            'PHY SCI',
            'PHYSICS',
            'POL SCI',
            'PSYCH',
            'STATS',
            'SWE',
        ],
    },
    {
        url: 'https://instagram.com/campkesemucirvine',
        bannerName: 'Kesem.png',
        dept: ['any'],
    },
    {
        url: 'https://discord.gg/eTwRpKv',
        bannerName: 'UCIDiscord.png',
        dept: ['any'],
    },
    {
        url: 'https://www.ucipanhellenic.com/recruitment-registration',
        bannerName: 'Panhellenic.png',
        dept: ['any'],
    },
    {
        url: 'https://vermillionvocalists.wixsite.com/vermillionvocalists',
        bannerName: 'Vermillion.png',
        dept: [
            'ART',
            'ART HIS',
            'ARTS',
            'ARTSHUM',
            'BIO SCI',
            'DANCE',
            'DRAMA',
            'ENGR',
            'FLM&MDA',
            'HUMAN',
            'HUMARTS',
            'MATH',
            'MUSIC',
            'PSCI',
            'PSYCH',
            'UNI STU',
        ],
    },
    {
        url: 'https://circleoffifthsuci.wixsite.com/circleoffifthsuci',
        bannerName: 'Fifth.png',
        dept: ['any'],
    },
    {
        url: 'https://www.facebook.com/groups/uci.open.jam/',
        bannerName: 'Open.png',
        dept: ['any'],
    },
    {
        url: 'https://www.thetatauuci.com/',
        bannerName: 'ThetaTau.png',
        dept: [
            'BME',
            'CBE',
            'COMPSCI',
            'CSE',
            'EECS',
            'ENGR',
            'ENGRCEE',
            'ENGRMAE',
            'ENGRMSE',
            'I&C SCI',
            'IN4MATX',
            'SWE',
        ],
        endDate: '2021-04-01',
    },
    {
        url: 'https://sites.uci.edu/codepath/',
        bannerName: 'CodePath.png',
        dept: [
            'BME',
            'CBE',
            'COGS',
            'COMPSCI',
            'CSE',
            'ECPS',
            'EECS',
            'ENGR',
            'ENGRCEE',
            'ENGRMAE',
            'ENGRMSE',
            'I&C SCI',
            'IN4MATX',
            'LSCI',
            'MATH',
            'NET SYS',
            'STATS',
            'SWE',
        ],
        endDate: '2021-03-29',
    },
    {
        url: 'https://forms.gle/CV76joocyRScFEcx5',
        bannerName: 'SASA.png',
        dept: ['any'],
        endDate: '2021-04-03',
    },
    {
        url: 'https://tinyurl.com/antalmanacxbannerads',
        bannerName: 'ad_for_ads.png',
        dept: ['any'],
    },
];
