name: 'Wait for Stack Stabilize'
description: 'Wait for all in-progress operations in the stack to complete'
inputs:
    stack_name:
        required: true

outputs:
    stack-exists:
        value: ${{ steps.check-stack-exists.outcome == 'success' && !steps.wait-for-stack-delete.outcome == 'success'}}

runs:
    using: 'composite'
    steps:
        - name: check if stack exists
          id: check-stack-exists
          run: echo "STACK_STATUS=$(aws cloudformation describe-stacks --stack-name ${{ inputs.stack_name }} --query "Stacks[0].StackStatus" --output text)" >> $GITHUB_ENV
          continue-on-error: true
          shell: bash

        - name: wait for stack create
          id: wait-for-stack-create
          if: steps.check-stack-exists.outcome == 'success' && env.STACK_STATUS == 'CREATE_IN_PROGRESS'
          run: aws cloudformation wait stack-create-complete --stack-name ${{ inputs.stack_name }}
          continue-on-error: true
          shell: bash

        - name: wait for stack update
          id: wait-for-stack-update
          if: steps.check-stack-exists.outcome == 'success' && env.STACK_STATUS == 'UPDATE_IN_PROGRESS'
          run: aws cloudformation wait stack-update-complete --stack-name ${{ inputs.stack_name }}
          continue-on-error: true
          shell: bash

        - name: wait for stack delete
          id: wait-for-stack-delete
          if: steps.check-stack-exists.outcome == 'success' && env.STACK_STATUS == 'DELETE_IN_PROGRESS'
          run: aws cloudformation wait stack-delete-complete --stack-name ${{ inputs.stack_name }}
          continue-on-error: true
          shell: bash
