import 'leaflet/dist/leaflet.css'
import 'react-big-calendar/lib/css/react-big-calendar.css'
import 'leaflet-routing-machine/dist/leaflet-routing-machine.css'
import 'leaflet.locatecontrol/dist/L.Control.Locate.min.css'
import '$components/Map/Map.css'
import '$components/Calendar/Calendar.css'

import Head from 'next/head'
import dynamic from 'next/dynamic'
import type { AppProps } from 'next/app'
import { SnackbarProvider } from 'notistack'
import AppQueryProvider from '$providers/Query'
import Header from '$components/Header'
import useHotkeys from '$hooks/useHotkeys'
import useGoogleAnalytics from '$hooks/useGoogleAnalytics'
import useUnsavedChanges from '$hooks/useUnsavedChanges'

/**
 * the theme relies on fetching data from local storage,
 * which causes classNames to be de-synced from the server -> turn SSR off
 */
const AppThemeProvider = dynamic(() => import('$providers/Theme'), { ssr: false })

export default function App({ Component, pageProps }: AppProps) {
  useHotkeys()
  useGoogleAnalytics()
  useUnsavedChanges()

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <AppQueryProvider>
        {/** @ts-expect-error Server Component @see {@link https://github.com/vercel/next.js/issues/42292} */}
        <AppThemeProvider>
          <SnackbarProvider>
            <Header />
            <Component {...pageProps} />
          </SnackbarProvider>
        </AppThemeProvider>
      </AppQueryProvider>
    </>
  )
}
