# iOS 17.4 is required for ASWebAuthenticationSession's `.https(host:path:)`
# Universal-Link callback, which we use for OAuth redirect. Custom URL schemes
# (antalmanac://) are spoofable across apps; Universal Links are bound to an
# app via the AASA file on antalmanac.com so callbacks can only be delivered
# to the AASA-verified AntAlmanac binary.
platform :ios, '17.4'

target 'AntAlmanac' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Add the pod for Firebase Cloud Messaging
  pod 'Firebase/Messaging'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.4'
    end
  end
end