name: Deployment Status
description: Manages GitHub deployment status for a PR

inputs:
    step:
        description: 'Deployment step: create, in_progress, success, or failure'
        required: true
    deployment-id:
        description: 'Deployment ID (required for in_progress, success, failure steps)'
        required: false
    environment:
        description: 'Environment name (required for create step)'
        required: false
    environment-url:
        description: 'Environment URL (required for success step)'
        required: false
    description:
        description: 'Deployment description'
        required: false
    sha:
        description: 'Git SHA to deploy (defaults to current SHA)'
        required: false
        default: ${{ github.sha }}
    production:
        description: 'Is this a production environment?'
        required: false
        default: 'false'

outputs:
    deployment-id:
        description: 'The deployment ID (only set during create step)'
        value: ${{ steps.create.outputs.result }}

runs:
    using: composite
    steps:
        - name: Create deployment
          id: create
          if: inputs.step == 'create'
          uses: actions/github-script@v7
          with:
              script: |
                  const deployment = await github.rest.repos.createDeployment({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      ref: '${{ inputs.sha }}',
                      environment: '${{ inputs.environment }}',
                      description: '${{ inputs.description }}',
                      auto_merge: false,
                      required_contexts: [],
                      production_environment: ${{ inputs.production }}
                  });
                  return deployment.data.id;
              result-encoding: string

        - name: Update deployment status
          if: inputs.step != 'create'
          uses: actions/github-script@v7
          with:
              script: |
                  const statusConfig = {
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      deployment_id: '${{ inputs.deployment-id }}',
                      state: '${{ inputs.step }}',
                      description: '${{ inputs.description }}'
                  };

                  // Add environment_url for success state
                  if ('${{ inputs.step }}' === 'success' && '${{ inputs.environment-url }}') {
                      statusConfig.environment_url = '${{ inputs.environment-url }}';
                  }

                  await github.rest.repos.createDeploymentStatus(statusConfig);
