export const DEPARTMENT_MAP = {
    ALL: 'ALL: Include All Departments',
    'AC ENG': 'AC ENG: Academic English and ESL',
    AFAM: 'AFAM: African American Studies',
    ANATOMY: 'ANATOMY: Anatomy and Neurobiology',
    ANESTH: 'ANESTH: Anesthesiology',
    ANTHRO: 'ANTHRO: Anthropology',
    ARABIC: 'ARABIC: Arabic',
    ARMN: 'ARMN: Armenian',
    ART: 'ART: Art',
    'ART HIS': 'ART HIS: Art History',
    ARTS: 'ARTS: Arts',
    ARTSHUM: 'ARTSHUM: Arts and Humanities',
    ASIANAM: 'ASIANAM: Asian American Studies',
    BANA: 'BANA: Business Analytics',
    BATS: 'BATS: Biomedical and Translational Science',
    'BIO SCI': 'BIO SCI: Biological Sciences',
    BIOCHEM: 'BIOCHEM: Biological Chemistry',
    BME: 'BME: Biomedical Engineering',
    CAMPREC: 'CAMPREC: Campus Recreation',
    CBE: 'CBE: Chemical and Biomolecular Engineering',
    CEM: 'CEM: Community and Environmental Medicine',
    'CHC/LAT': 'CHC/LAT: Chicano Latino',
    CHEM: 'CHEM: Chemistry',
    CHINESE: 'CHINESE: Chinese',
    CLASSIC: 'CLASSIC: Classics',
    'CLT&THY': 'CLT&THY: Culture & Theory',
    COGS: 'COGS: Cognitive Sciences',
    'COM LIT': 'COM LIT: Comparative Literature',
    COMPSCI: 'COMPSCI: Computer Science',
    CRITISM: 'CRITISM: Criticism',
    'CRM/LAW': 'CRM/LAW: Criminology, Law and Society',
    CSE: 'CSE: Computer Science and Engineering',
    DANCE: 'DANCE: Dance',
    DERM: 'DERM: Dermatology',
    'DEV BIO': 'DEV BIO: Developmental and Cell Biology',
    DRAMA: 'DRAMA: Drama',
    EARTHSS: 'EARTHSS: Earth System Science',
    EAS: 'EAS: East Asian Studies',
    'ECO EVO': 'ECO EVO: Ecology and Evolutionary Biology',
    ECON: 'ECON: Economics',
    ECPS: 'ECPS: Embedded and Cyber-Physical Systems',
    'ED AFF': 'ED AFF: Educational Affairs (Sch of Med)',
    EDUC: 'EDUC: Education',
    EECS: 'EECS: Electrical Engineering & Computer Science',
    EHS: 'EHS: Environmental Health Sciences',
    ENGLISH: 'ENGLISH: English',
    ENGR: 'ENGR: Engineering',
    ENGRCEE: 'ENGRCEE: Engineering, Civil and Environmental',
    ENGRMAE: 'ENGRMAE: Engineering, Mechanical and Aerospace',
    EPIDEM: 'EPIDEM: Epidemiology',
    'ER MED': 'ER MED: Emergency Medicine',
    'EURO ST': 'EURO ST: European Studies',
    'FAM MED': 'FAM MED: Family Medicine',
    FIN: 'FIN: Finance',
    'FLM&MDA': 'FLM&MDA: Film and Media Studies',
    FRENCH: 'FRENCH: French',
    GDIM: 'GDIM: Game Design and Interactive Media',
    'GEN&SEX': 'GEN&SEX: Gender and Sexuality Studies',
    GERMAN: 'GERMAN: German',
    'GLBL ME': 'GLBL ME: Global Middle East Studies',
    GLBLCLT: 'GLBLCLT: Global Cultures',
    GREEK: 'GREEK: Greek',
    HEBREW: 'HEBREW: Hebrew',
    HINDI: 'HINDI: Hindi',
    HISTORY: 'HISTORY: History',
    HUMAN: 'HUMAN: Humanities',
    HUMARTS: 'HUMARTS: Humanities and Arts',
    'I&C SCI': 'I&C SCI: Information and Computer Science',
    IN4MATX: 'IN4MATX: Informatics',
    INNO: 'INNO: Masters of Innovation and Entrepreneurship',
    'INT MED': 'INT MED: Internal Medicine',
    'INTL ST': 'INTL ST: International Studies',
    IRAN: 'IRAN: Iranian',
    ITALIAN: 'ITALIAN: Italian',
    JAPANSE: 'JAPANSE: Japanese',
    KOREAN: 'KOREAN: Korean',
    LATIN: 'LATIN: Latin',
    LAW: 'LAW: Law',
    'LIT JRN': 'LIT JRN: Literary Journalism',
    LPS: 'LPS: Logic and Philosophy of Science',
    LSCI: 'LSCI: Language Science',
    'M&MG': 'M&MG: Microbiology and Molecular Genetics',
    MATH: 'MATH: Mathematics',
    MED: 'MED: Medicine',
    'MED ED': 'MED ED: Medical Education',
    'MED HUM': 'MED HUM: Medical Humanities',
    MGMT: 'MGMT: Management',
    'MGMT EP': 'MGMT EP: Executive MBA',
    'MGMT FE': 'MGMT FE: Fully Employed MBA',
    'MGMT HC': 'MGMT HC: Health Care MBA',
    MGMTMBA: 'MGMTMBA: Management MBA',
    MGMTPHD: 'MGMTPHD: Management PhD',
    'MIC BIO': 'MIC BIO: Microbiology',
    'MOL BIO': 'MOL BIO: Molecular Biology and Biochemistry',
    MPAC: 'MPAC: Accounting',
    MSE: 'MSE: Materials Science and Engineering',
    MUSIC: 'MUSIC: Music',
    'NET SYS': 'NET SYS: Networked Systems',
    NEURBIO: 'NEURBIO: Neurobiology and Behavior',
    NEUROL: 'NEUROL: Neurology',
    'NUR SCI': 'NUR SCI: Nursing Science',
    'OB/GYN': 'OB/GYN: Obstetrics and Gynecology',
    OPHTHAL: 'OPHTHAL: Ophthalmology',
    PATH: 'PATH: Pathology and Laboratory Medicine',
    'PED GEN': 'PED GEN: Pediatrics Genetics',
    PEDS: 'PEDS: Pediatrics',
    PERSIAN: 'PERSIAN: Persian',
    PHARM: 'PHARM: Medical Pharmacology',
    PHILOS: 'PHILOS: Philosophy',
    PHRMSCI: 'PHRMSCI: Pharmaceutical Sciences',
    'PHY SCI': 'PHY SCI: Physical Science',
    PHYSICS: 'PHYSICS: Physics',
    PHYSIO: 'PHYSIO: Physiology and Biophysics',
    PLASTIC: 'PLASTIC: Plastic Surgery',
    'PM&R': 'PM&R: Physical Medicine and Rehabilitation',
    'POL SCI': 'POL SCI: Political Science',
    PORTUG: 'PORTUG: Portuguese',
    PSCI: 'PSCI: Psychological Science',
    PSYCH: 'PSYCH: Psychology',
    'PUB POL': 'PUB POL: Public Policy',
    PUBHLTH: 'PUBHLTH: Public Health',
    RADIO: 'RADIO: Radiology',
    'REL STD': 'REL STD: Religious Studies',
    ROTC: "ROTC: Reserve Officers' Training Corps",
    RUSSIAN: 'RUSSIAN: Russian',
    'SOC SCI': 'SOC SCI: Social Science',
    SOCECOL: 'SOCECOL: Social Ecology',
    SOCIOL: 'SOCIOL: Sociology',
    SPANISH: 'SPANISH: Spanish',
    SPPS: 'SPPS: Social Policy & Public Service',
    STATS: 'STATS: Statistics',
    SURGERY: 'SURGERY: Surgery',
    SWE: 'SWE: Software Engineering',
    TAGALOG: 'TAGALOG: Tagalog',
    TOX: 'TOX: Toxicology',
    UCDC: 'UCDC: UC Washington DC',
    'UNI AFF': 'UNI AFF: University Affairs',
    'UNI STU': 'UNI STU: University Studies',
    UPPP: 'UPPP: Urban Planning and Public Policy',
    VIETMSE: 'VIETMSE: Vietnamese',
    'VIS STD': 'VIS STD: Visual Studies',
    WRITING: 'WRITING: Writing',
} as const;
