import type {DepartmentSearchResult, SearchResult} from '@packages/antalmanac-types';

// TODO implement codegen for this at CI time

export const departmentKeys = ["ac eng","afam","anatomy","anthro","arabic","armn","art","art his","arts","asianam","bana","bats","biochem","bio sci","bme","cbe","cbems","chc/lat","chem","chinese","classic","clt&thy","cogs","com lit","compsci","critism","crm/law","cse","dance","data","dev bio","drama","earthss","eas","e asian","eco evo","econ","ecps","educ","eecs","ehs","english","engr","engrcee","engrmae","engrmse","epidem","euro st","fin","flm&mda","french","gdim","gen&sex","german","glblclt","glbl me","greek","hebrew","history","human","i&c sci","in4matx","inno","intl st","iran","italian","japanse","korean","latin","linguis","lit jrn","lps","lsci","math","med hum","mgmt","mgmt ep","mgmt fe","mgmt hc","mgmtmba","mgmtphd","m&mg","mol bio","mpac","mse","music","net sys","neurbio","nur sci","path","ped gen","persian","pharm","philos","phmd","phrmsci","phy sci","physics","physio","pol sci","portug","pp&d","psci","psy beh","psych","pubhlth","pub pol","rel std","rotc","russian","socecol","sociol","soc sci","spanish","spps","stats","swe","tox","ucdc","uni aff","uni stu","uppp","vietmse","vis std","womn st","writing"] as const;

export type DepartmentKey = (typeof departmentKeys)[number];

export const departmentAliasKeys = ["aceng","arthis","biosci","chclat","cltthy","comlit","crmlaw","cs","devbio","easian","ecoevo","ess","eurost","flmmda","gensex","glblme","ics","inf","intlst","litjrn","medhum","mgmtep","mgmtfe","mgmthc","mmg","molbio","netsys","nursci","pedgen","physci","polsci","ppd","psybeh","pubpol","relstd","socsci","uniaff","unistu","visstd","womnst","wr"] as const;

export type DepartmentAliasKey = (typeof departmentAliasKeys)[number];

export const departmentAliases: Record<DepartmentAliasKey, DepartmentKey> = {
    aceng: 'ac eng',
    arthis: 'art his',
    biosci: 'bio sci',
    chclat: 'chc/lat',
    cltthy: 'clt&thy',
    comlit: 'com lit',
    crmlaw: 'crm/law',
    cs: 'compsci',
    devbio: 'dev bio',
    easian: 'e asian',
    ecoevo: 'eco evo',
    ess: 'earthss',
    eurost: 'euro st',
    flmmda: 'flm&mda',
    gensex: 'gen&sex',
    glblme: 'glbl me',
    ics: 'i&c sci',
    inf: 'in4matx',
    intlst: 'intl st',
    litjrn: 'lit jrn',
    medhum: 'med hum',
    mgmtep: 'mgmt ep',
    mgmtfe: 'mgmt fe',
    mgmthc: 'mgmt hc',
    mmg: 'm&mg',
    molbio: 'mol bio',
    netsys: 'net sys',
    nursci: 'nur sci',
    pedgen: 'ped gen',
    physci: 'phy sci',
    polsci: 'pol sci',
    ppd: 'pp&d',
    psybeh: 'psy beh',
    pubpol: 'pub pol',
    relstd: 'rel std',
    socsci: 'soc sci',
    uniaff: 'uni aff',
    unistu: 'uni stu',
    visstd: 'vis std',
    womnst: 'womn st',
    wr: 'writing',
};

const departments: Record<DepartmentKey, DepartmentSearchResult> = {
    'ac eng': { type: 'DEPARTMENT', name: 'Academic English' },
    afam: { type: 'DEPARTMENT', name: 'African American Studies' },
    anatomy: { type: 'DEPARTMENT', name: 'Anatomy and Neurobiology' },
    anthro: { type: 'DEPARTMENT', name: 'Anthropology' },
    arabic: { type: 'DEPARTMENT', name: 'Arabic' },
    armn: { type: 'DEPARTMENT', name: 'Armenian' },
    art: { type: 'DEPARTMENT', name: 'Art' },
    'art his': { type: 'DEPARTMENT', name: 'Art History' },
    arts: { type: 'DEPARTMENT', name: 'Arts' },
    asianam: { type: 'DEPARTMENT', name: 'Asian American Studies' },
    bana: { type: 'DEPARTMENT', name: 'Business Analytics' },
    bats: { type: 'DEPARTMENT', name: 'Biomedical and Translational Science' },
    biochem: { type: 'DEPARTMENT', name: 'Biological Chemistry' },
    'bio sci': { type: 'DEPARTMENT', name: 'Biological Sciences' },
    bme: { type: 'DEPARTMENT', name: 'Biomedical Engineering' },
    cbe: { type: 'DEPARTMENT', name: 'Chemical and Biomolecular Engineering' },
    cbems: { type: 'DEPARTMENT', name: 'Chemical Engineering and Materials Science' },
    'chc/lat': { type: 'DEPARTMENT', name: 'Chicano/Latino Studies' },
    chem: { type: 'DEPARTMENT', name: 'Chemistry' },
    chinese: { type: 'DEPARTMENT', name: 'Chinese' },
    classic: { type: 'DEPARTMENT', name: 'Classics' },
    'clt&thy': { type: 'DEPARTMENT', name: 'Culture and Theory' },
    cogs: { type: 'DEPARTMENT', name: 'Cognitive Sciences' },
    'com lit': { type: 'DEPARTMENT', name: 'Comparative Literature' },
    compsci: { type: 'DEPARTMENT', name: 'Computer Science' },
    critism: { type: 'DEPARTMENT', name: 'Criticism' },
    'crm/law': { type: 'DEPARTMENT', name: 'Criminology, Law and Society' },
    cse: { type: 'DEPARTMENT', name: 'Computer Science and Engineering' },
    dance: { type: 'DEPARTMENT', name: 'Dance' },
    data: { type: 'DEPARTMENT', name: 'Data Science' },
    'dev bio': { type: 'DEPARTMENT', name: 'Developmental and Cell Biology' },
    drama: { type: 'DEPARTMENT', name: 'Drama' },
    earthss: { type: 'DEPARTMENT', name: 'Earth System Science' },
    eas: { type: 'DEPARTMENT', name: 'East Asian Studies' },
    'e asian': { type: 'DEPARTMENT', name: 'East Asian Languages and Literatures' },
    'eco evo': { type: 'DEPARTMENT', name: 'Ecology and Evolutionary Biology' },
    econ: { type: 'DEPARTMENT', name: 'Economics' },
    ecps: { type: 'DEPARTMENT', name: 'Embedded and Cyber-Physical Systems' },
    educ: { type: 'DEPARTMENT', name: 'Education' },
    eecs: { type: 'DEPARTMENT', name: 'Electrical Engineering & Computer Science' },
    ehs: { type: 'DEPARTMENT', name: 'Environmental Health Sciences' },
    english: { type: 'DEPARTMENT', name: 'English' },
    engr: { type: 'DEPARTMENT', name: 'Engineering' },
    engrcee: { type: 'DEPARTMENT', name: 'Civil and Environmental Engineering' },
    engrmae: { type: 'DEPARTMENT', name: 'Mechanical and Aerospace Engineering' },
    engrmse: { type: 'DEPARTMENT', name: 'Materials Science and Engineering' },
    epidem: { type: 'DEPARTMENT', name: 'Epidemiology' },
    'euro st': { type: 'DEPARTMENT', name: 'European Studies' },
    fin: { type: 'DEPARTMENT', name: 'Finance' },
    'flm&mda': { type: 'DEPARTMENT', name: 'Film and Media Studies' },
    french: { type: 'DEPARTMENT', name: 'French' },
    gdim: { type: 'DEPARTMENT', name: 'Game Design and Interactive Media' },
    'gen&sex': { type: 'DEPARTMENT', name: 'Gender and Sexuality Studies' },
    german: { type: 'DEPARTMENT', name: 'German' },
    glblclt: { type: 'DEPARTMENT', name: 'Global Cultures' },
    'glbl me': { type: 'DEPARTMENT', name: 'Global Middle East Studies' },
    greek: { type: 'DEPARTMENT', name: 'Greek' },
    hebrew: { type: 'DEPARTMENT', name: 'Hebrew' },
    history: { type: 'DEPARTMENT', name: 'History' },
    human: { type: 'DEPARTMENT', name: 'Humanities' },
    'i&c sci': { type: 'DEPARTMENT', name: 'Information and Computer Science' },
    in4matx: { type: 'DEPARTMENT', name: 'Informatics' },
    inno: { type: 'DEPARTMENT', name: 'Innovation and Entrepreneurship' },
    'intl st': { type: 'DEPARTMENT', name: 'International Studies' },
    iran: { type: 'DEPARTMENT', name: 'Iranian Studies' },
    italian: { type: 'DEPARTMENT', name: 'Italian' },
    japanse: { type: 'DEPARTMENT', name: 'Japanese' },
    korean: { type: 'DEPARTMENT', name: 'Korean' },
    latin: { type: 'DEPARTMENT', name: 'Latin' },
    linguis: { type: 'DEPARTMENT', name: 'Linguistics' },
    'lit jrn': { type: 'DEPARTMENT', name: 'Literary Journalism' },
    lps: { type: 'DEPARTMENT', name: 'Logic and Philosophy of Science' },
    lsci: { type: 'DEPARTMENT', name: 'Language Science' },
    math: { type: 'DEPARTMENT', name: 'Mathematics' },
    'med hum': { type: 'DEPARTMENT', name: 'Medical Humanities' },
    mgmt: { type: 'DEPARTMENT', name: 'Management' },
    'mgmt ep': { type: 'DEPARTMENT', name: 'Executive MBA' },
    'mgmt fe': { type: 'DEPARTMENT', name: 'Fully Employed MBA' },
    'mgmt hc': { type: 'DEPARTMENT', name: 'Health Care MBA' },
    mgmtmba: { type: 'DEPARTMENT', name: 'Management MBA' },
    mgmtphd: { type: 'DEPARTMENT', name: 'Management PhD' },
    'm&mg': { type: 'DEPARTMENT', name: 'Microbiology and Molecular Genetics' },
    'mol bio': { type: 'DEPARTMENT', name: 'Molecular Biology and Biochemistry' },
    mpac: { type: 'DEPARTMENT', name: 'Master of Professional Accountancy' },
    mse: { type: 'DEPARTMENT', name: 'Materials Science and Engineering' },
    music: { type: 'DEPARTMENT', name: 'Music' },
    'net sys': { type: 'DEPARTMENT', name: 'Networked Systems' },
    neurbio: { type: 'DEPARTMENT', name: 'Neurobiology and Behavior' },
    'nur sci': { type: 'DEPARTMENT', name: 'Nursing Science' },
    path: { type: 'DEPARTMENT', name: 'Pathology and Laboratory Medicine' },
    'ped gen': { type: 'DEPARTMENT', name: 'Pediatrics Genetics' },
    persian: { type: 'DEPARTMENT', name: 'Persian' },
    pharm: { type: 'DEPARTMENT', name: 'Medical Pharmacology' },
    philos: { type: 'DEPARTMENT', name: 'Philosophy' },
    phmd: { type: 'DEPARTMENT', name: 'Pharmacy' },
    phrmsci: { type: 'DEPARTMENT', name: 'Pharmaceutical Sciences' },
    'phy sci': { type: 'DEPARTMENT', name: 'Physical Science' },
    physics: { type: 'DEPARTMENT', name: 'Physics' },
    physio: { type: 'DEPARTMENT', name: 'Physiology and Biophysics' },
    'pol sci': { type: 'DEPARTMENT', name: 'Political Science' },
    portug: { type: 'DEPARTMENT', name: 'Portuguese' },
    'pp&d': { type: 'DEPARTMENT', name: 'Planning, Policy, and Design' },
    psci: { type: 'DEPARTMENT', name: 'Psychological Science' },
    'psy beh': { type: 'DEPARTMENT', name: 'Psychology and Social Behavior' },
    psych: { type: 'DEPARTMENT', name: 'Psychology' },
    pubhlth: { type: 'DEPARTMENT', name: 'Public Health' },
    'pub pol': { type: 'DEPARTMENT', name: 'Public Policy' },
    'rel std': { type: 'DEPARTMENT', name: 'Religious Studies' },
    rotc: { type: 'DEPARTMENT', name: "Reserve Officers' Training Corps" },
    russian: { type: 'DEPARTMENT', name: 'Russian' },
    socecol: { type: 'DEPARTMENT', name: 'Social Ecology' },
    sociol: { type: 'DEPARTMENT', name: 'Sociology' },
    'soc sci': { type: 'DEPARTMENT', name: 'Social Science' },
    spanish: { type: 'DEPARTMENT', name: 'Spanish' },
    spps: { type: 'DEPARTMENT', name: 'Social Policy and Public Service' },
    stats: { type: 'DEPARTMENT', name: 'Statistics' },
    swe: { type: 'DEPARTMENT', name: 'Software Engineering' },
    tox: { type: 'DEPARTMENT', name: 'Toxicology' },
    ucdc: { type: 'DEPARTMENT', name: 'UC Washington DC' },
    'uni aff': { type: 'DEPARTMENT', name: 'University Affairs' },
    'uni stu': { type: 'DEPARTMENT', name: 'University Studies' },
    uppp: { type: 'DEPARTMENT', name: 'Urban Policy and Public Planning' },
    vietmse: { type: 'DEPARTMENT', name: 'Vietnamese' },
    'vis std': { type: 'DEPARTMENT', name: 'Visual Studies' },
    'womn st': { type: 'DEPARTMENT', name: "Women's Studies" },
    writing: { type: 'DEPARTMENT', name: 'Writing' },
};

export const toDepartment = (key: DepartmentKey | DepartmentAliasKey): [string, SearchResult] =>
    [(departmentAliases[key as DepartmentAliasKey] ?? key).toUpperCase(), departments[departmentAliases[key as DepartmentAliasKey] ?? key]];
