name: Delete - Staging Monorepo

on:
    workflow_dispatch:

concurrency:
    group: sst-staging-monorepo
    cancel-in-progress: false

env:
    AWS_REGION: ${{ secrets.AWS_REGION }}

    DB_URL: ${{ secrets.DEV_DB_URL }}
    MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
    ANTEATER_API_KEY: ${{ secrets.ANTEATER_API_KEY }}
    OIDC_CLIENT_ID: ${{ secrets.OIDC_CLIENT_ID }}
    OIDC_ISSUER_URL: ${{ secrets.OIDC_ISSUER_URL }}
    PLANNER_CLIENT_API_KEY: ${{ secrets.PLANNER_CLIENT_API_KEY }}

    PLANNER_DATABASE_URL: ${{ secrets.PLANNER_DEV_DATABASE_URL }}
    PLANNER_SESSION_SECRET: ${{ secrets.PLANNER_SESSION_SECRET }}
    PLANNER_ADMIN_EMAILS: ${{ secrets.PLANNER_ADMIN_EMAILS }}
    PLANNER_PUBLIC_API_URL: https://anteaterapi.com/v2/rest/
    PLANNER_EXTERNAL_USER_READ_SECRET: ${{ secrets.PLANNER_CLIENT_API_KEY }}
    PLANNER_NEXT_PUBLIC_POSTHOG_KEY: ${{ secrets.NEXT_PUBLIC_PUBLIC_POSTHOG_KEY }}
    PLANNER_NEXT_PUBLIC_POSTHOG_HOST: https://us.i.posthog.com

jobs:
    destroy:
        runs-on: ubuntu-latest
        env:
            SST_STAGE: staging-monorepo

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: monorepo

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Setup Node.js and pnpm
              uses: ./.github/actions/setup-node-and-pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            # TODO (@xgraceyan): Remove this stage once SST fixes deployments
            - name: Setup Pulumi
              uses: pulumi/actions@v5
              with:
                  pulumi-version: 3.138.0 # Any version < 3.214.0 works

            - name: Remove SST staging-monorepo
              run: |
                  echo "Removing stage: $SST_STAGE"
                  npx sst remove --stage "$SST_STAGE"
